In [752]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import tree
from sklearn.model_selection import GridSearchCV
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import *
from sklearn import *
from sklearn.metrics import accuracy_score
from sklearn.linear_model import *
from pandas import *
from datetime import date
from sklearn import *
from sklearn.impute import SimpleImputer

from sklearn.feature_extraction.text import *
from sklearn.naive_bayes import *
from sklearn.metrics import *
from scipy import *

# load the data
df = pd.read_csv('/home/giang/Downloads/gianha/train.csv')
df_test = pd.read_csv('/home/giang/Downloads/gianha/test.csv')

In [753]:
# thong tin
df.info()
df
# tong dong co null
# df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [754]:
df = df.drop('Id',axis=1)
x = df.drop('SalePrice',axis=1)
y = df['SalePrice']

In [755]:
x.head(20)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
5,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal
6,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
7,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,Shed,350,11,2009,WD,Normal
8,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml
9,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,1,2008,WD,Normal
10,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
11,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,7,2006,New,Partial
12,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,Inside,...,176,0,NaN,NaN,NaN,0,9,2008,WD,Normal
13,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,8,2007,New,Partial
14,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,GdWo,NaN,0,5,2008,WD,Normal
15,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal
16,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,0,NaN,NaN,Shed,700,3,2010,WD,Normal
17,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,Shed,500,10,2006,WD,Normal
18,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal
19,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml

In [756]:
y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [757]:
# chu va so
numerical_col = []
cat_col = []
for i in x.columns:
    if x[i].dtype == 'object':
        cat_col.append(i)
        print(i+': ' + str(len(x[i].unique())))
    else:
        numerical_col.append(i)
        
print('CAT col \n', cat_col)
print('Numerical col\n')
print(numerical_col)

MSZoning: 5
Street: 2
Alley: 3
LotShape: 4
LandContour: 4
Utilities: 2
LotConfig: 5
LandSlope: 3
Neighborhood: 25
Condition1: 9
Condition2: 8
BldgType: 5
HouseStyle: 8
RoofStyle: 6
RoofMatl: 8
Exterior1st: 15
Exterior2nd: 16
MasVnrType: 5
ExterQual: 4
ExterCond: 5
Foundation: 6
BsmtQual: 5
BsmtCond: 5
BsmtExposure: 5
BsmtFinType1: 7
BsmtFinType2: 7
Heating: 6
HeatingQC: 5
CentralAir: 2
Electrical: 6
KitchenQual: 4
Functional: 7
FireplaceQu: 6
GarageType: 7
GarageFinish: 4
GarageQual: 6
GarageCond: 6
PavedDrive: 3
PoolQC: 4
Fence: 5
MiscFeature: 5
SaleType: 9
SaleCondition: 6
CAT col
 ['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']
Numerical col

['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold']

In [758]:
xx = pd.get_dummies(df.LotConfig)
xx

      Corner  CulDSac  FR2  FR3  Inside
0          0        0    0    0       1
1          0        0    1    0       0
2          0        0    0    0       1
3          1        0    0    0       0
4          0        0    1    0       0
...      ...      ...  ...  ...     ...
1455       0        0    0    0       1
1456       0        0    0    0       1
1457       0        0    0    0       1
1458       0        0    0    0       1
1459       0        0    0    0       1

[1460 rows x 5 columns]

In [759]:
# chuyen doi bien phan loai thanh bien gia
xc = pd.get_dummies(x)
xc

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,1999,2000,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1456,20,85.0,13175,6,6,1978,1988,119.0,790,163,...,0,0,0,1,0,0,0,0,1,0
1457,70,66.0,9042,7,9,1941,2006,0.0,275,0,...,0,0,0,1,0,0,0,0,1,0
1458,20,68.0,9717,5,6,1950,1996,0.0,49,1029,...,0,0,0,1,0,0,0,0,1,0
1459,20,75.0,9937,5,6,1965,1965,0.0,830,290,...,0,0,0,1,0,0,0,0,1,0

In [760]:
for c in cat_col:
    le = LabelEncoder() 
    x[c] = le.fit_transform(list(x[c].values))

In [762]:
# x = xc
x.head(20)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,3,65.0,8450,1,2,3,3,0,4,...,0,0,3,4,4,0,2,2008,8,4
1,20,3,80.0,9600,1,2,3,3,0,2,...,0,0,3,4,4,0,5,2007,8,4
2,60,3,68.0,11250,1,2,0,3,0,4,...,0,0,3,4,4,0,9,2008,8,4
3,70,3,60.0,9550,1,2,0,3,0,0,...,0,0,3,4,4,0,2,2006,8,0
4,60,3,84.0,14260,1,2,0,3,0,2,...,0,0,3,4,4,0,12,2008,8,4
5,50,3,85.0,14115,1,2,0,3,0,4,...,0,0,3,2,2,700,10,2009,8,4
6,20,3,75.0,10084,1,2,3,3,0,4,...,0,0,3,4,4,0,8,2007,8,4
7,60,3,NaN,10382,1,2,0,3,0,0,...,0,0,3,4,2,350,11,2009,8,4
8,50,4,51.0,6120,1,2,3,3,0,4,...,0,0,3,4,4,0,4,2008,8,0
9,190,3,50.0,7420,1,2,3,3,0,0,...,0,0,3,4,4,0,1,2008,8,4
10,20,3,70.0,11200,1,2,3,3,0,4,...,0,0,3,4,4,0,2,2008,8,4
11,60,3,85.0,11924,1,2,0,3,0,4,...,0,0,3,4,4,0,7,2006,6,5
12,20,3,NaN,12968,1,2,1,3,0,4,...,176,0,3,4,4,0,9,2008,8,4
13,20,3,91.0,10652,1,2,0,3,0,4,...,0,0,3,4,4,0,8,2007,6,5
14,20,3,NaN,10920,1,2,0,3,0,0,...,0,0,3,1,4,0,5,2008,8,4
15,45,4,51.0,6120,1,2,3,3,0,0,...,0,0,3,0,4,0,7,2007,8,4
16,20,3,NaN,11241,1,2,0,3,0,1,...,0,0,3,4,2,700,3,2010,8,4
17,90,3,72.0,10791,1,2,3,3,0,4,...,0,0,3,4,2,500,10,2006,8,4
18,20,3,66.0,13695,1,2,3,3,0,4,...,0,0,3,4,4,0,6,2008,8,4
19,20,3,70.0,7560,1,2,3,3,0,4,...,0,0,3,2,4,0,5,2009,0,0

In [763]:
# x.SalePrice
# df.info()

In [764]:
# x = x.drop('SalePrice',axis=1)

In [765]:
# dien cac gia tri con thieu theo gia tri trung binh
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imputer.fit(x)
x = imputer.transform(x)
# y = imputer.transform(y[numerical_col])

In [766]:
# chuan hoa theo min max
scl = MinMaxScaler()
x = scl.fit_transform(x)
x

array([[0.23529412, 0.75      , 0.15068493, ..., 0.5       , 1.        ,
        0.8       ],
       [0.        , 0.75      , 0.20205479, ..., 0.25      , 1.        ,
        0.8       ],
       [0.23529412, 0.75      , 0.1609589 , ..., 0.5       , 1.        ,
        0.8       ],
       ...,
       [0.29411765, 0.75      , 0.15410959, ..., 1.        , 1.        ,
        0.8       ],
       [0.        , 0.75      , 0.1609589 , ..., 1.        , 1.        ,
        0.8       ],
       [0.        , 0.75      , 0.18493151, ..., 0.5       , 1.        ,
        0.8       ]])

In [767]:
# chia tap ti le 8, 2
X_train , X_test , y_train , y_test = train_test_split(x , y , test_size= 0.2, random_state = 42)

In [768]:
y_train

254     145000
1066    178000
638      85000
799     175000
380     127000
         ...
1095    176432
1130    135000
1294    115000
860     189950
1126    174000
Name: SalePrice, Length: 1168, dtype: int64

In [769]:
X_test

array([[0.        , 0.75      , 0.16780822, ..., 0.        , 1.        ,
        0.8       ],
       [0.23529412, 0.75      , 0.26369863, ..., 1.        , 1.        ,
        0.8       ],
       [0.05882353, 1.        , 0.11986301, ..., 1.        , 1.        ,
        0.8       ],
       ...,
       [0.23529412, 0.75      , 0.14383562, ..., 0.5       , 1.        ,
        0.8       ],
       [0.29411765, 0.75      , 0.13356164, ..., 0.75      , 1.        ,
        0.8       ],
       [0.        , 0.75      , 0.16780822, ..., 0.75      , 1.        ,
        0.8       ]])

In [770]:
y_test

892     154500
1105    325000
413     115000
522     159000
1036    315500
         ...
479      89471
1361    260000
802     189000
651     108000
722     124500
Name: SalePrice, Length: 292, dtype: int64

In [771]:
clf = LinearRegression(normalize=True)
res = clf.fit(X_train, y_train)

In [772]:
scores = clf.score(X_test, y_test)
scores

0.8436229454048209

In [773]:
resS = res.predict(X_test)
resS[1]

320266.5503500427

In [774]:
y_test.values.tolist()
# df.values.tolist()

[154500,
 325000,
 115000,
 159000,
 315500,
 75500,
 311500,
 146000,
 84500,
 135500,
 145000,
 130000,
 81000,
 214000,
 181000,
 134500,
 183500,
 135000,
 118400,
 226000,
 155000,
 210000,
 173500,
 129000,
 192000,
 153900,
 181134,
 141000,
 181000,
 208900,
 127000,
 284000,
 200500,
 135750,
 255000,
 140000,
 138000,
 219500,
 310000,
 97000,
 114500,
 205000,
 119500,
 253293,
 128500,
 117500,
 115000,
 127000,
 451950,
 144000,
 119000,
 196000,
 115000,
 287000,
 144500,
 260000,
 213000,
 175000,
 107000,
 107500,
 68500,
 154000,
 317000,
 264132,
 283463,
 243000,
 109000,
 305000,
 93500,
 176000,
 118858,
 134000,
 109008,
 93500,
 611657,
 173000,
 348000,
 341000,
 141000,
 124900,
 118000,
 67000,
 113000,
 91300,
 149500,
 133000,
 266000,
 190000,
 155900,
 155835,
 153500,
 152000,
 124500,
 301000,
 136500,
 169990,
 205000,
 183900,
 204900,
 260000,
 163500,
 224900,
 244000,
 132000,
 194000,
 156500,
 156000,
 275000,
 145000,
 135000,
 60000,
 124000,
 127000,
 137500,
 213500,
 119000,
 107900,
 123000,
 112000,
 284000,
 133000,
 149000,
 169000,
 207000,
 175000,
 137000,
 236000,
 79500,
 144000,
 162900,
 185900,
 369900,
 197900,
 104000,
 35311,
 337500,
 367294,
 130250,
 230000,
 755000,
 403000,
 132000,
 178000,
 136500,
 145000,
 123000,
 250000,
 187100,
 133900,
 67000,
 137500,
 155000,
 200624,
 154300,
 91000,
 136000,
 108959,
 140000,
 86000,
 131400,
 179900,
 144000,
 293077,
 144500,
 118500,
 141000,
 239000,
 276000,
 556581,
 244400,
 360000,
 103200,
 102000,
 151000,
 285000,
 134432,
 113000,
 187500,
 125500,
 177500,
 179900,
 55993,
 132500,
 135000,
 255000,
 140000,
 271000,
 246578,
 202500,
 75000,
 122500,
 108480,
 160000,
 171000,
 196000,
 225000,
 197000,
 40000,
 172500,
 154900,
 280000,
 175000,
 147000,
 315000,
 185000,
 135500,
 239500,
 139000,
 140000,
 110000,
 225000,
 143500,
 128950,
 172500,
 241500,
 262500,
 194201,
 143000,
 130000,
 126000,
 142500,
 254000,
 217500,
 66500,
 201000,
 155000,
 68400,
 64500,
 173000,
 102776,
 84900,
 165600,
 120000,
 135000,
 220000,
 153575,
 195400,
 147000,
 277000,
 143000,
 105900,
 242000,
 194500,
 438780,
 185000,
 107500,
 165000,
 176000,
 129900,
 115000,
 192140,
 160000,
 145000,
 86000,
 158000,
 127500,
 115000,
 119500,
 175900,
 240000,
 395000,
 165000,
 128200,
 275000,
 311872,
 214000,
 153500,
 144000,
 115000,
 180000,
 465000,
 180000,
 253000,
 85000,
 101800,
 148500,
 137500,
 318061,
 143000,
 140000,
 192500,
 92000,
 197000,
 109500,
 297000,
 185750,
 230000,
 89471,
 260000,
 189000,
 108000,
 124500]

In [775]:
print(mean_squared_error(y_test, clf.predict(X_test)))

1199463020.0641344

In [776]:
def mape(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [777]:
mape_ = mape(y_test, resS)
mape_

12.863089411673458